# Generated by Django 6.0.5 on 2026-05-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_status_order_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gcash_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
